version: '3'
services:
  paralexproject-airflow:
    image: paralexproject:latest
    build: .
    volumes:
      - ./airflow:/opt/airflow
      # FIX: Mount the dbt project folder into the container
      - ./paralex_project:/opt/airflow/paralex_project
    ports:
      - "8080:8080"
    command: airflow standalone
    depends_on:
      - postgres-data

  postgres-data:
    image: postgres:15
    container_name: postgres-paralex-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432" 
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data

volumes:
  postgres_db_volume: